### ISSUE TITLE
hazelcast rest interface can't be enabled

### ISSUE THREAD

**Issue by dgroverWintac** [pires/hazelcast-kubernetes#11]
In hazelcast 3.7 the rest interface is disabled by default and there doesn't seem to be a way to enable it while running this image.

**Comment by pires** [comment]
@dgroverWintac a PR would definitely help fixing that. Or at least provide documentation that shows how to enable this feature.

**Comment by hotstepper13** [comment]
Because this is a spring-boot environment, it might be enough to add an application.yml to the jar containing hazelcast.rest.enabled=true to enable it permanent.

If done like 
    hazelcast.rest.enabled=${env.hazelcast.rest.enable:false}

you have the same situation as now, but should be able to overwrite this by defining an environment variable
    ENV_HAZELCAST_REST_ENABLE=true

I will try this and might provide a PR for this.

**Comment by pires** [comment]
Cool! I'll be waiting on it @hotstepper13.

**Comment by hotstepper13** [comment]
The application yml wasnt working but i managed to set it otherwise. Now i have to figure out how to create a PR :(

**Comment by pires** [comment]
Fixed by https://github.com/pires/hazelcast-kubernetes-bootstrapper/pull/13. Will make a release in the coming hours.
